version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  debug:
    addr: 127.0.0.1:5001
  draintimeout: 30s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
